// react/trading-ui/src/component/NavBar/NavBar.jsx
import React from 'react'
import './NavBar.scss'
import { NavLink } from 'react-router-dom'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAddressBook as dashboardIcon } from '@fortawesome/free-solid-svg-icons';
import { faMoneyBill as quoteIcon } from '@fortawesome/free-solid-svg-icons';


function NavBar() {
  return (
    <nav className="page-navigation">
		    <NavLink to="/" className="page-navigation-header"></NavLink>    
		    <NavLink to="/dashboard" className="page-navigation-item">
		        <FontAwesomeIcon icon={ dashboardIcon } />
		    </NavLink>    
        <NavLink to="/quotes" className="page-navigation-item">
    <FontAwesomeIcon icon={quoteIcon} />
</NavLink>

    </nav>
  )
}

export default NavBar

// angular/angular_tradingApp/angular-trading-ui/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
//import { faAddressBook } from '@fortawesome/free-solid-svg-icons';
import { faAddressBook, faMoneyBillWave } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  faAddressBook = faAddressBook;
  faMoney = faMoneyBillWave;
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="nav-body">
  <div class="nav-item">
    <a routerLink="/dashboard">
      <fa-icon [icon]="faAddressBook" size="2x"></fa-icon> 
    </a>   
  </div>
  <div class="nav-item">
    <a routerLink="/quotes">
      <fa-icon [icon]="faMoney" size="2x"></fa-icon>
    </a>
  </div>
</div>
